cmake_minimum_required(VERSION 3.10)
project(PIS-GUI VERSION 1.0.0 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_AUTOMOC ON)
find_package(Qt5 REQUIRED COMPONENTS Widgets)
set(PIS_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../src)
set(PIS_INC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../include)
add_executable(pis_gui main.cpp pis_window.cpp ${PIS_SRC_DIR}/pis_config.cpp ${PIS_SRC_DIR}/pis_schedule.cpp ${PIS_SRC_DIR}/pis_display.cpp ${PIS_SRC_DIR}/utils.cpp)
target_link_libraries(pis_gui Qt5::Widgets pthread)
target_include_directories(pis_gui PRIVATE ${CMAKE_CURRENT_SOURCE_DIR} ${PIS_INC_DIR})
